cookie:
  expiry_days: 0.1
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      logged_in: false
      name: John Smith
      password: $2b$12$.4dptfE7zFrTbBM16pmk7ejVw8e4kwp1rISsE10UdubmduBiZVuIS
    krish10:
      email: kbarman1015@gmail.com
      logged_in: false
      name: Krishnendu Barman
      password: $2b$12$13W8Ph8zI/XdawTkF5peUOpkJDqMExizb4NCEk33VxsVx.spQNyM2
    rbriggs:
      email: rbriggs@gmail.com
      logged_in: false
      name: Rebecca Briggs
      password: $2b$12$/1vXN0ORGgWrJvwyFcNX..KLUQWIswsKLjRdJWWOAQiHijrDvHq2m
preauthorized:
  emails:
    - melsby@gmail.com
